# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Clever Vision 
# Description of the Site
description: Experts in Computer Vision.
description-long: We create state-of-the-art Deep Learning solutions and customize them to your needs. 

# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Computer Vision, Machine Vision, Deep Learning, Machine Learning, Artificial Intelligence 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: clevervision@gmail.com
twitter_username: clevervision
instagram_username: 
linkedin_username: 
github_username:  clevervision
youtube_channel_id: 
 

# Google Analytics
google-analytics: 


company-name: Clever Vision
company-logo: /assets/images/cv_logo.png
company-about: We are a group of passionate AI engineers who love researching and face new challenges every time. We develop state-of-the-art solutions in Computer Vision to deal with real world problems.

author-image1: /assets/images/uri.jpg
author-about1: Esteban Uriza. MSc in Computer Science from the University of de Buenos Aires. He enjoys researching new technologies and algorithms exploiting the possibilities offered by Machine Learning, Computer Vision, AI tools, to create great features for applications. 
author-image2: /assets/images/ubalde.jpg
author-about2: Sebastián Ubalde. PhD in Computer Science from the University of de Buenos Aires. Hiring talent to democratize the commerce, money and payments in Latin America 
author-image3: /assets/images/pachi.jpg
author-about3: Francisco Gómez-Fernández. PhD in Computer Science from the University of de Buenos Aires. He has participated as PI and project leader in various technology transfer projects in Argentina. Funded by CONICET, he completed a two years postdoctoral research project under the supervision of Prof. Taubin working on new methods for 3D point cloud simplification, surface reconstruction and 3D scanning.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/clevervision

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
